apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-nodeport
spec:
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP
  clusterIP: 192.168.3.84
  selector:
    name: nginx
  type: NodePort
